In [5]:
import numpy as np
import gym
import random

In [2]:
env = gym.make("Taxi-v2")
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [3]:
action_size = env.action_space.n
print(action_size)

s_s = env.observation_space.n
print(s_s)

6
500


In [6]:
qtable = np.zeros((s_s, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
total_ep = 50000
total_test_ep = 100
max_steps = 99

lr = 0.7
g = 0.618
eps = 1.0
max_eps = 1.0
min_eps = 0.1
decay_rate = 0.01


In [18]:
for ep in range(total_ep):
    s = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0,1)
        
        if exp_exp_tradeoff > eps:
            action = np.argmax(qtable[s, :])
        
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        qtable[s, action] = qtable[s, action] + lr * (reward + g * np.max(qtable[new_state, :]) - qtable[s, action])
        
        s = new_state
        
        if done == True:
            break
    
    ep += 1
    
    eps = min_eps + (max_eps - min_eps) * np.exp(-decay_rate * ep)
    
        

In [19]:
qtable

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ -1.89494435,  -1.44813002,  -1.89494435,  -1.44813002,
         -0.72512948, -10.44813002],
       [ -0.72512948,   0.4447743 ,  -0.72512948,   0.4447743 ,
          2.33782249,  -8.5552257 ],
       ...,
       [  2.33782249,   5.40100727,   2.33782249,   0.4447743 ,
         -6.66217751,  -6.66217751],
       [ -1.89494435,  -1.44813002,  -1.89494435,  -1.44813002,
        -10.89494435, -10.89494435],
       [ 18.37802094,  10.35761694,  18.37802094,  31.35602094,
          9.37802094,   9.37802094]])

In [20]:
env.reset()
rewards = []

for ep in range(total_test_ep):
    s = env.reset()
    step = 0
    done = False
    total_rewards = 0
    print("******************************************")
    print("EPISODE", ep)
    
    for step in range(max_steps):
        env.render()
        action = np.argmax(qtable[s,:])
        new_state, reward, done, info = env.step(action)
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            print("Score", total_rewards)
            break
        s = new_state
env.close
print("Score over time" + str(sum(rewards)/total_test_ep))


******************************************
EPISODE 0
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | :

+---------+
|R:_| : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
Score 6
******************************************
EPISODE 74
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------